### ISSUE TITLE
"Official" Handlebars docset

### ISSUE THREAD

**Issue by Kapeli** [giladgray/dash-handlebars-docset#1]
Hi @giladgray. This is just a heads-up that a Handlebars docset made by me will be released in the next Dash update. Please let me know what you would like to happen with your Handlebars docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/Handlebars.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by giladgray** [comment]
@Kapeli looks great! More than happy for you to support this in a first party way. I'll add a note to this repo, not that anyone ever looks here.
